### PR TITLE
Update from Intelsdi-x pluginsync 0.1.6

### PR DESCRIPTION
**Pull request by nanliu**

### CODE REVIEW

**Comment by nanliu** [comment]
This plugin needs pcm.x binary and this PR is on hold until I sort out a way to build or fetch it.

**Comment by nanliu** [comment]
This plugin is not reasonable to run in travis based on this output:
```
Access to Intel(r) Performance Counter Monitor has denied (Performance Monitoring Unit is occupied by other application). Try to stop the application that uses PMU.
```

We will need to consider alternative test platforms or just mocking out the tests.

**Comment by kindermoumoute** [comment]
Even before, tests were not working on Travis. I would keep only build test on Travis until https://github.com/intelsdi-x/snap-plugin-collector-pcm/issues/7 got fixed.

**Comment by nanliu** [comment]
Disabled test on travis and documented reason in .sync.yml.

**Pull request merged**
